<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <InternalsVisibleTo Include="RIoT2.Net.Devices.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" />
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="Microsoft.Azure.Relay" />
    <PackageReference Include="RIoT2.Core" />
    <PackageReference Include="Zhaobang.FtpServer" />
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
